# Generated by Django 3.0.4 on 2020-03-31 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('slot_from', models.TimeField()),
                ('slot_to', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commandes.DeliveryLocation')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_type', models.CharField(choices=[('U', 'unit(s)'), ('W', 'Kg')], max_length=1)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commandes.Cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='commandes.Delivery'),
        ),
    ]
