# Generated by Django 3.0.4 on 2020-03-31 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_initial_cart_and_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'cart', 'verbose_name_plural': 'carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'delivery', 'verbose_name_plural': 'deliveries'},
        ),
        migrations.AlterModelOptions(
            name='deliverylocation',
            options={'verbose_name': 'delivery location', 'verbose_name_plural': 'delivery locations'},
        ),
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='article',
            name='label',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='article',
            name='unit_type',
            field=models.CharField(choices=[('U', 'unit(s)'), ('W', 'Kg')], default='W', max_length=1, verbose_name='unit type'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commandes.Cart', verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commandes.DeliveryLocation', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='deliverylocation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
