# Generated by Django 3.0.4 on 2020-04-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_bind_cart_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('10', 'received'), ('20', 'preparation in progress'), ('30', 'prepared'), ('40', 'delivered'), ('50', 'abandoned')], default='10', verbose_name='status'),
        ),
    ]
