# Generated by Django 3.0.4 on 2020-03-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('label', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_type', models.CharField(choices=[('U', 'unit(s)'), ('W', 'Kg')], default='W', max_length=1)),
            ],
        ),
    ]
