# Generated by Django 3.0.4 on 2020-03-31 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_verbose_names_i18n'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'permissions': [('view_delivery_quantities', 'View needed quantities for a delivery')], 'verbose_name': 'delivery', 'verbose_name_plural': 'deliveries'},
        ),
    ]
