# Generated by Django 3.0.4 on 2020-04-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0007_cart_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'permissions': [('prepare_basket', 'Prepare basket')], 'verbose_name': 'cart', 'verbose_name_plural': 'carts'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'received'), (20, 'preparation in progress'), (30, 'prepared'), (40, 'delivered'), (50, 'abandoned')], default=10, verbose_name='status'),
        ),
    ]
