# Generated by Django 3.0.4 on 2020-04-05 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baskets', '0009_group_permission_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('presentation', models.TextField(blank=True, default='', verbose_name='presentation')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'merchant',
                'verbose_name_plural': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(max_length=255, verbose_name='URL')),
                ('url_type', models.CharField(choices=[('F', 'Facebook'), ('E', 'Email address'), ('P', 'Phone number'), ('W', 'Website')], default='W', max_length=1, verbose_name='URL type')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='baskets.Merchant', verbose_name='merchant')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
            },
        ),
    ]
