# Generated by Django 3.0.4 on 2020-04-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0014_refactor_delivery_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='max_per_slot',
            field=models.PositiveSmallIntegerField(default=0, help_text='Set 0 for unlimited carts per slot', verbose_name='maximum number of baskets per slot'),
        ),
    ]
